### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by MohyiddineDilmi** [albertocasagrande/pyModelChecking#1]
Hello friend,
Could you please help me to test your project because i have some problems in language file,
can you give instructions to run model checking file.
Greeting,
Mohyiddine

**Comment by albertocasagrande** [comment]
There was an encoding issue in the test directory. I fixed the bug and new it should works as expected. 

To install the package execute the following command as superuser:
``
python setup.py install
``

Then, you can reproduce the examples reported in the main page simply by copying and pasting them in the Python shell.

**Comment by MohyiddineDilmi** [comment]
Thank you very much
