### ISSUE TITLE
U formula LTL

### ISSUE THREAD

**Issue by Loryerba** [albertocasagrande/pyModelChecking#14]
Hi im trying to check this formula q U r in LTL.
I tried this
phi = parser('q U r')

print(modelcheck(K,phi))

but it doesn't work. 
expected a LTL state formula, got (q U r)
  File "C:\Users\Lorenzo\Desktop\modelcheck\main.py", line 12, in <module>
    print(modelcheck(K,phi))
          ~~~~~~~~~~^^^^^^^
TypeError: expected a LTL state formula, got (q U r)

But if i print(phi.__class__) is correct U formula.

**Comment by albertocasagrande** [comment]
`q U p` is an LTL path formula, i.e., it expresses a property of *a path*, but `modelcheck()` only deals with state formulas, i.e., formulas describing properties of *a state* (e.g., `q U p` holds over all the paths from the considered state`).

Have a look at [this page](https://pymodelchecking.readthedocs.io/en/latest/logics.html#linear-time-logic).

Replace `q U p` with `A(q U p)` to search for all the states whose leaving paths satisfy `q U p`.
