### ISSUE TITLE
Publish the package on conda-forge

### ISSUE THREAD

**Issue by xtrojak** [albertocasagrande/pyModelChecking#5]
Publishing via [conda-forge](https://github.com/conda-forge/staged-recipes) would be great contribution for the tool.

**Comment by xtrojak** [comment]
In progress [here](https://github.com/conda-forge/staged-recipes/pull/17978).

**Comment by albertocasagrande** [comment]
Great job. Thank you.

**Comment by xtrojak** [comment]
You are welcome. Please let me know if you would like to be listed as [the recipe maintainer](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role).

**Comment by albertocasagrande** [comment]
No time, too many projects...
